module scenebuilder.kit {
    requires java.prefs;
    requires java.logging;
    requires javafx.base;
    requires javafx.fxml;
    requires transitive javafx.controls;
    requires javafx.graphics;
    requires javafx.media;
    requires javafx.web;
    requires javafx.swing;

    opens com.oracle.javafx.scenebuilder.kit.editor.panel.content to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.editor.panel.css to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.editor.panel.hierarchy.treeview to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.editor.panel.inspector to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.editors to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.popupeditors to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.editor.panel.library to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.editor.panel.util to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.editor.panel.util.dialog to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.editor.job to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.editor.search to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.fxom to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.metadata to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.metadata.property.value.list to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.metadata.util to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.util to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.util.control.effectpicker to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.util.control.effectpicker.editors to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.util.control.paintpicker to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.util.control.paintpicker.colorpicker to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.util.control.paintpicker.gradientpicker to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.util.control.paintpicker.rotator to javafx.fxml;
    opens com.oracle.javafx.scenebuilder.kit.util.control.paintpicker.slider to javafx.fxml;

    exports com.oracle.javafx.scenebuilder.kit.editor;
    exports com.oracle.javafx.scenebuilder.kit.editor.drag;
    exports com.oracle.javafx.scenebuilder.kit.editor.drag.source;
    exports com.oracle.javafx.scenebuilder.kit.editor.drag.target;
    exports com.oracle.javafx.scenebuilder.kit.editor.i18n;
    exports com.oracle.javafx.scenebuilder.kit.editor.images;
    exports com.oracle.javafx.scenebuilder.kit.editor.job;
    exports com.oracle.javafx.scenebuilder.kit.editor.job.atomic;
    exports com.oracle.javafx.scenebuilder.kit.editor.job.gridpane;
    exports com.oracle.javafx.scenebuilder.kit.editor.job.reference;
    exports com.oracle.javafx.scenebuilder.kit.editor.job.togglegroup;
    exports com.oracle.javafx.scenebuilder.kit.editor.job.wrap;
    exports com.oracle.javafx.scenebuilder.kit.editor.job.gridpane.v2;
    exports com.oracle.javafx.scenebuilder.kit.editor.messagelog;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.gridpane;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.handles;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.outline;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.pring;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.relocater;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.resizer;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.resizer.shape;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.rudder;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.driver.tring;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.gesture;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.gesture.key;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.gesture.mouse;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.guides;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.mode;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.content.util;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.css;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.hierarchy;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.hierarchy.treeview;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.inspector;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.editors;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.popupeditors;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.library;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.util;
    exports com.oracle.javafx.scenebuilder.kit.editor.panel.util.dialog;
    exports com.oracle.javafx.scenebuilder.kit.editor.report;
    exports com.oracle.javafx.scenebuilder.kit.editor.search;
    exports com.oracle.javafx.scenebuilder.kit.editor.selection;
    exports com.oracle.javafx.scenebuilder.kit.editor.util;
    exports com.oracle.javafx.scenebuilder.kit.fxom;
    exports com.oracle.javafx.scenebuilder.kit.fxom.glue;
    exports com.oracle.javafx.scenebuilder.kit.fxom.sampledata;
    exports com.oracle.javafx.scenebuilder.kit.glossary;
    exports com.oracle.javafx.scenebuilder.kit.library;
    exports com.oracle.javafx.scenebuilder.kit.library.user;
    exports com.oracle.javafx.scenebuilder.kit.library.util;
    exports com.oracle.javafx.scenebuilder.kit.metadata;
    exports com.oracle.javafx.scenebuilder.kit.metadata.klass;
    exports com.oracle.javafx.scenebuilder.kit.metadata.property;
    exports com.oracle.javafx.scenebuilder.kit.metadata.property.value;
    exports com.oracle.javafx.scenebuilder.kit.metadata.property.value.effect;
    exports com.oracle.javafx.scenebuilder.kit.metadata.property.value.effect.light;
    exports com.oracle.javafx.scenebuilder.kit.metadata.property.value.keycombination;
    exports com.oracle.javafx.scenebuilder.kit.metadata.property.value.list;
    exports com.oracle.javafx.scenebuilder.kit.metadata.property.value.paint;
    exports com.oracle.javafx.scenebuilder.kit.metadata.util;
    exports com.oracle.javafx.scenebuilder.kit.util;
    exports com.oracle.javafx.scenebuilder.kit.util.control.effectpicker;
    exports com.oracle.javafx.scenebuilder.kit.util.control.effectpicker.editors;
    exports com.oracle.javafx.scenebuilder.kit.util.control.paintpicker;
    exports com.oracle.javafx.scenebuilder.kit.util.control.paintpicker.colorpicker;
    exports com.oracle.javafx.scenebuilder.kit.util.control.paintpicker.gradientpicker;
    exports com.oracle.javafx.scenebuilder.kit.util.control.paintpicker.rotator;
    exports com.oracle.javafx.scenebuilder.kit.util.control.paintpicker.slider;
}
